language: python
python:
  - "2.6"
  - "2.7"
install:
  - ./bootstrap.py
  - pip install coveralls
script:
  - ./manage.py test
branches:
    except:
        - /feature\/*/
after_success:
  - coveralls
