language: python
python:
  - "2.6"
  - "2.7"
install:
  - ./bootstrap.py
script:
  - ./manage.py test mediathread.djangosherd
  - ./manage.py test mediathread.assetmgr
  - ./manage.py test mediathread.projects
  - ./manage.py test mediathread.main
