language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - git submodule update --init --recursive
install:
  - ./bootstrap.py
script:
  - ./manage.py test reports --settings=settings_test
  - ./manage.py test structuredcollaboration --settings=settings_test
