language: python
python:
  - "2.6"
  - "2.7"
install:
  - ./bootstrap.py
  - pip install python-coveralls
script:
  - ./manage.py test --with-coverage
branches:
    except:
        - /feature\/*/
after_success:
  - coveralls
