---

- name: Add nginx repo key
  apt_key: url=http://nginx.org/keys/nginx_signing.key

- name: Add nginx repo
  apt_repository: repo="{{item}}"
  with_items:
    - deb http://nginx.org/packages/ubuntu/ precise nginx
    - deb-src http://nginx.org/packages/ubuntu/ precise nginx

- name: Install nginx
  apt: pkg=nginx state=latest

- name: Ensure main Nginx configuration file is up to date
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Remove default virtual hosts
  file: path=/etc/nginx/conf.d/{{item}}.conf state=absent
  with_items:
    - default
    - example_ssl

- name: Create virtual hosts folders
  file: path=/etc/nginx/{{item}} state=directory
  with_items:
    - sites-available
    - sites-enabled

- name: Copy the virtual host config file
  template: src=nginx_uwsgi.conf dest=/etc/nginx/sites-available/{{app_name}}.conf

- name: Enable the virtual host
  file: path=/etc/nginx/sites-enabled/{{app_name}}.conf src=/etc/nginx/sites-available/{{app_name}}.conf state=link
  notify:
    - restart nginx
