---

- name: Add nginx repo key
  apt_key: url=http://nginx.org/keys/nginx_signing.key

- name: Add nginx repo
  apt_repository: repo="{{item}}"
  with_items:
    - deb http://nginx.org/packages/ubuntu/ precise nginx
    - deb-src http://nginx.org/packages/ubuntu/ precise nginx

- name: Install nginx
  apt: pkg=nginx state=latest
  notify:
    - restart nginx

- name: Ensure main Nginx configuration file is up to date
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Remove default virtual hosts
  file: path=/etc/nginx/conf.d/{{item}}.conf state=absent
  with_items:
    - default
    - example_ssl

- name: Create virtual hosts folders
  file: path=/etc/nginx/{{item}} state=directory
  with_items:
    - sites-available
    - sites-enabled

- name: Check if SSL cert is present
  local_action: stat path="{{inventory_dir}}/{{ item }}"
  sudo: False
  with_items:
    - server.key
    - server.crt
  register: certs

- name: Copy the real SSL certificate
  copy: src={{inventory_dir}}/{{item.item}} dest=/etc/nginx/
  with_items: certs.results
  when: item.stat.exists

- name: Copy the self signed SSL certificate
  copy: src={{item.item}} dest=/etc/nginx/
  with_items: certs.results
  when: not item.stat.exists
  notify:
    - restart nginx

- name: Copy the virtual host config file
  template: src=nginx_uwsgi.conf dest=/etc/nginx/sites-available/{{app_name}}.conf
  notify:
    - restart nginx

- name: Enable the virtual host
  file: path=/etc/nginx/sites-enabled/{{app_name}}.conf src=/etc/nginx/sites-available/{{app_name}}.conf state=link

- name: Increase the TCP buffer
  sysctl: name="net.ipv4.tcp_max_syn_backlog" value=2048 reload=yes
