---
# file: site.yml
- hosts: server
  remote_user: "{{remote_user}}"
  gather_facts: false
  roles:
    - common
    - pythondev
    - postgresql
    - memcached
    - nginx
    - uwsgi
    - app_deployment
    - newrelic
    - supervisor
